### ISSUE TITLE
Android Pad 端拖拽页签异常问题

### ISSUE THREAD

**Issue by Soltus** [Hi-Windom/winsay#120]
拖拽不能改变位置，页签变透明且无法恢复

**Comment by Soltus** [comment]
关联 #114

**Comment by Soltus** [comment]
![image](https://user-images.githubusercontent.com/83791825/197475075-56fd0e9c-7a67-4902-b72c-e48d1ac9ee8a.png)

**Comment by Soltus** [comment]
解决方案为：屏蔽 Android 端拖拽

**Comment by Soltus** [comment]
前置条件：
在 theme.js 中
<pre>
window.theme.OS = window.siyuan.config.system.os;
document.body.classList.add(window.theme.OS);
</pre>

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/6405
