### ISSUE TITLE
Android Pad 端竖屏状态下【设置】-【快捷键】布局问题

### ISSUE THREAD

**Issue by Soltus** [Hi-Windom/winsay#130]
![c7dfcaf0c9044c53511820866a66581](https://user-images.githubusercontent.com/83791825/197565272-4aaccc9b-0f6a-4347-9906-8c89fcedbc8c.jpg)

**Comment by Soltus** [comment]
Android Pad 端无法捕获键盘输入（未尝试实体键盘），因此直接隐藏即可

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/6417
