### ISSUE TITLE
【设置】-【集市】filter 宽度缩窄

### ISSUE THREAD

**Issue by Soltus** [Hi-Windom/winsay#143]
![image](https://user-images.githubusercontent.com/83791825/197705372-400a6e02-5b4f-4eff-80a7-e9930781cc97.png)

适配 Android Pad 端竖屏状态显示效果

**Comment by Soltus** [comment]
类似： #130

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/6417
