### ISSUE TITLE
文档树字号自适应面板宽度

### ISSUE THREAD

**Issue by tcmtom** [Hi-Windom/winsay#343]
![image](https://user-images.githubusercontent.com/94541098/201107899-409d437c-9655-4c09-8dd8-0d37524e863c.png)
红与绿对比

**Comment by Soltus** [comment]
> ![image](https://user-images.githubusercontent.com/94541098/201107899-409d437c-9655-4c09-8dd8-0d37524e863c.png) 红与绿对比

考虑到多层级显示效果，文档树面板宽度小于 360px 时固定为 9.5 磅字号，v0.100 将调整文档树面板宽度大于 360px 时的字号，最大 12 磅，届时你可以手动调整面板宽度来调整字号

**Comment by tcmtom** [comment]
还是小了点，能把基础的大小提高一点吗？

**Comment by tcmtom** [comment]
> > 还是小了点，能把基础的大小提高一点吗？
> 
> 后续支持通过主题设置面板进行设置，敬请期待

好，辛苦大佬
