### ISSUE TITLE
更新后标题栏上面搜索设置这些的按钮变的十分巨大

### ISSUE THREAD

**Issue by a674709300** [Hi-Windom/winsay#379]
退出重进，重装主题都试了。用 Dark 主题在更新浮动工具栏的个版本也有遇到过类似的问题，但是通过禁用缓存刷新后可以恢复，这边我也试了下，不行。
![图片](https://user-images.githubusercontent.com/13486247/201517865-5c2fb916-3f28-4b97-b189-72e5577119f9.png)

**Comment by Soltus** [comment]
> 退出重进，重装主题都试了。用 Dark 主题在更新浮动工具栏的个版本也有遇到过类似的问题，但是通过禁用缓存刷新后可以恢复，这边我也试了下，不行。 ![图片](https://user-images.githubusercontent.com/13486247/201517865-5c2fb916-3f28-4b97-b189-72e5577119f9.png)

这是已知问题，在最新的0.110版本已经修复，等集市更新版本了看看吧

**Comment by a674709300** [comment]
好的，非常感谢 (❁´◡`❁)
