### ISSUE TITLE
优化行内代码彩蛋触发逻辑

### ISSUE THREAD

**Issue by a674709300** [Hi-Windom/winsay#381]
英文结尾会导致中文字间距变宽，希望能直接末尾留空，像这样：
![图片](https://user-images.githubusercontent.com/13486247/201519115-14c573e7-5f09-4b20-8aae-a6805b3ce55e.png)

而且这里如果把鼠标移到 `IGameplayTagAssetInterface` 上，段落会高频来会伸缩。
![Animation](https://user-images.githubusercontent.com/13486247/201519248-7095a402-514f-4e05-a009-775006059352.gif)

**Comment by Soltus** [comment]
麻烦提供一下文档

**Comment by a674709300** [comment]
是指的这段文本吗？

**Comment by a674709300** [comment]
# 二、`ItemDefinition`

**作用：**
用于储存数据的 DataAsset，但并没有继承自 `UPrimaryDataAsset`，而是自己重写 `GetPrimaryAssetId` 以及实现 `IGameplayTagAssetInterface` 来达到 DataAsset 效果
**分为：**
**数据** (最大堆叠大小、Tag)、 **显示** (模型与 UI 数据为)、**逻辑** (默认堆栈类) 三个部分

**Comment by Soltus** [comment]
我这里无法复现，麻烦检查一下主题版本和思源版本，以及看看开发者工具里的控制台有没有报错。你截图里的样式有些不一样
，我这里是正常效果：
![image](https://user-images.githubusercontent.com/83791825/201519894-ea0ec31b-297e-4673-8348-f5ad5e58cbed.png)

**Comment by Soltus** [comment]
伸缩问题已定位

**Comment by Soltus** [comment]
支持通过

- #382 

关闭
