### ISSUE TITLE
支持通过主题设置界面配置图片块背景色

### ISSUE THREAD

**Issue by Soltus** [Hi-Windom/winsay#488]
支持细化到聚焦态，能够改善暗黑模式下透明图片显示效果

**Comment by Soltus** [comment]
https://ld246.com/article/1668939506721

**Comment by luo-chuan** [comment]
最好就是允许用户指定某些图片是否反色显示，比如通过增加属性的方式，filter : invert(100%)

**Comment by luo-chuan** [comment]
或者建议对每个图片都能设置这样一个属性，那就是，是否在深色模式下反色显示。

**Comment by luo-chuan** [comment]
建议这样来实现
https://github.com/siyuan-note/siyuan/issues/6711

**Comment by Soltus** [comment]
@luo-chuan 
感谢提议，但是相比于白底方案，反色显示的适用范围过于小了，单独给图片设置的方案也不适合主题，
