### ISSUE TITLE
支持通过主题设置面板配置垂直页签栏自动收起

### ISSUE THREAD

**Issue by MoonBottle** [Hi-Windom/winsay#508]
目前焦点放到文档上后垂直标签页会自动收起，文档正文会随之移动，影响视线，希望可以设置不自动收起

**Comment by Soltus** [comment]
0.170改进 @MoonBottle

**Comment by Soltus** [comment]
![image](https://user-images.githubusercontent.com/83791825/202962523-fa510804-0bdc-4470-af72-eeb0d7228c55.png)

@MoonBottle

**Comment by MoonBottle** [comment]
效率真高 👍
