### ISSUE TITLE
自动切换代理服务器

### ISSUE THREAD

**Issue by oijqws** [Hi-Windom/winsay#513]
有时候需要上公司 VPN（只能通过代理上网），思源同步就不工作了，
如果同步的时候可以尝试先尝试代理服务器链接，在尝试直接连接，这样就可以无缝切换？
微信就是这样做的
否则 每次切换网络都要重新启动。
谢谢

**Comment by Soltus** [comment]
@oijqws 
这个需求主题无法实现，请在思源软件repo提 [issue](https://github.com/siyuan-note/siyuan/issues/new/choose)，或者前往社区 [发帖](https://ld246.com/domain/siyuan)
