### ISSUE TITLE
主题默认字体为加粗，导致文档中设置加粗样式无效果

### ISSUE THREAD

**Issue by MoonBottle** [Hi-Windom/winsay#518]
![image](https://user-images.githubusercontent.com/12904505/203017506-d5459950-d72e-46ee-9202-741b23a6fb84.png)

**Comment by MoonBottle** [comment]
建议调整下主题默认字体

**Comment by Soltus** [comment]
> 建议调整下主题默认字体

默认字体取决于本机设置，我这里微软雅黑是没有问题的

**Comment by MoonBottle** [comment]
抱歉抱歉，是我机器设置的问题，和主题无关
![Uploading image.png…]()

**Comment by Soltus** [comment]
> 抱歉抱歉，是我机器设置的问题，和主题无关 ![image](https://user-images.githubusercontent.com/12904505/203022837-75567422-ee34-4bcc-bef5-bd9bc547c8a8.png)

OK
