### ISSUE TITLE
HintHint限宽策略调整+支持通过主题设置界面配置HintHint限宽

### ISSUE THREAD

**Issue by clark874** [Hi-Windom/winsay#627]
还是昨天提出的问题，在左右界面两个菜单都开启的情况下，引用弹出的黑色菜单会遮挡文字输入。
<img width="1165" alt="2022-11-30 12 03 12" src="https://user-images.githubusercontent.com/86122040/204704874-519b7bb6-f744-42b4-b18a-85ebd18de10f.png">

**Comment by Soltus** [comment]
感谢反馈，今天下午解决
