### ISSUE TITLE
引用菜单遮挡问题

### ISSUE THREAD

**Issue by clark874** [Hi-Windom/winsay#649]
如题，更新到最新版后，遮挡问题仍然存在。这个弹出菜单的尺寸也显得很大，能不能缩小一些呢？
<img width="929" alt="2022-12-01 12 57 46" src="https://user-images.githubusercontent.com/86122040/204969137-ded54ccd-57af-421e-97e9-45d96aee8332.png">

**Comment by clark874** [comment]
<img width="604" alt="image" src="https://user-images.githubusercontent.com/86122040/205065418-e6356ca3-3036-43b0-946a-ee09b15dc158.png">
作者好，主题设置面板里没有hinthint面板限高和限宽选择。也没有最新更新的主题滤镜，不知道是为什么？我使用的是mac book pro版本，同时删除了外观文件直接下载的github0.236版本重装的。

**Comment by Soltus** [comment]
> <img alt="image" width="604" src="https://user-images.githubusercontent.com/86122040/205065418-e6356ca3-3036-43b0-946a-ee09b15dc158.png">
> 
> 作者好，主题设置面板里没有hinthint面板限高和限宽选择。也没有最新更新的主题滤镜，不知道是为什么？我使用的是mac book pro版本，同时删除了外观文件直接下载的github0.236版本重装的。

彻底删除后解压，而不是覆盖更新试试。如果仍没有，看一下开发者工具控制台有没有报错

**Comment by Soltus** [comment]
Mac系统应该就是被忽略掉了，麻烦单开一个 issue 反馈这个问题 @clark874
