### ISSUE TITLE
mac系统显示错误

### ISSUE THREAD

**Issue by clark874** [Hi-Windom/winsay#658]
<img width="1162" alt="2022-12-01 21 57 19" src="https://user-images.githubusercontent.com/86122040/205071329-17075bf9-2f92-4c75-8df3-1d038b986e8f.png">
版本0.236

**Comment by clark874** [comment]
<img width="1160" alt="2022-12-01 21 59 38" src="https://user-images.githubusercontent.com/86122040/205071864-a19ef1ec-e4d9-45eb-adcf-8eb3de16d350.png">
版本0.226

**Comment by Soltus** [comment]
我这里没有MAC机器，加我QQ远程看看吧

**Comment by Soltus** [comment]
我先关闭了，明天集市更新了你看看吧。
